---
title: "Covid-19 Analyzer"
author: "Yitong Zou, Yuting Chen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## 1. Use Case

* The Shiny App can analyze the changes in COVID-19 cases and deaths by country from January 22nd, 2020, to November 4th, 2021, and analyze the number of vaccinations by country from February 22nd, 2021, to November 4th, 2021. Secondly, this Shiny App can also compare the differences in the number of cases, deaths and vaccinations among countries. Thirdly, this Shiny App can show the heath care and poverty condition for each country. By knowing each country's heath care and poverty condition, we can find certain reasons that some countries have large number of cases and deaths or some countries don't have large number of cases and deaths.
* In addition, this shiny app is for people who care about COVID-19 or want to do research on each country's COVID-19 trends, so the users might be the government officials, COVID-19 researchers and the ordinary people who care about the COVID-19 situation.


## 2. Required Packages

* The packages used in this Shiny APP are {shiny}, {tidyverse}, {maps}, {ggplot2}, {RColorBrewer}, {ggthemes}, {shinythemes} and {fresh}.

* Packages version:
{shiny} 1.5.0, {tidyverse} 1.3.0, {maps} 3.3.0, {ggplot2} 3.3.2, {RColorBrewer} 1.1-2, {ggthemes} 4.2.0, {shinythemes} 1.2.0, {fresh} 0.2.0.


## 3. Data Source and Structure

### a. Data Source

* [COVID-19 cases, deaths and vaccinations by country over time](https://github.com/owid/covid-19-data/tree/master/public/data)

* [Data of heath care by country](https://ourworldindata.org/financing-healthcare)

* [Data of poverty by country](http://iresearch.worldbank.org/PovcalNet/data.aspx)


### b. Structure

Firstly, about the data of COVID-19. We tidied all of data sets about the number of cases, deaths and vaccinations into a new data set called "Total_Data_New". "Total_Data_New" includes each country's name, the continents for each country, date, the number of cases and deaths by country in each day from January 22nd, 2020, to November 4th, 2021, and the number of vaccinations by country in each day from February 22nd, 2021, to November 4th, 2021.
Secondly, about the data of health care. We have three data sets, which are about health expenditure per capita, the proportion of public health care and the ratio of total heath care to GDP. These data sets have countries' name, countries' code, year and values, which include each country's heath expenditure per capita, the proportion of public health care and the ratio of total heath care to GDP in each year.
Thirdly, about the data of poverty. We have one data set including each country's poverty situation in each year. This data set includes countries' name, countries' code, year, coverage type, poverty line and headcount. 


## 4. EDA Inputs, Controls, and Outputs

* Tab 1 shows the global COVID-19 situation. Tab1 has two little tabs. First little tab is a map, users can choose a type and a date that they want to know from the left sidebar. The type includes cases, deaths and vaccinations. Then, the main page will show the global map with the information that users have chose. For example, the user chooses type of "Cases" and date of "2021-11-04". Then, the main page can show the map of total number of COVID-19 cases in each country on November 4th in 2021. In addition, the second little tab shows the line plots about global or continents' cases or deaths. The users can choose a level which includes global and continent and can choose a type which includes cases and deaths in the left sidebar. Then, the main page will show a line plot. For example, if the user chooses "Global" and "Cases", the main page can show the line plot of total number of confirmed cases worldwide. If the user chooses "Continent" and "Cases", the main page can show a line plot of total number of confirmed cases by continent.

* Tab 2 shows information on the epidemic in a single country. First, the user can view the cumulative distribution of the data line plot. In the left screen, users can select countries to be observed, types of observations (cases, deaths, vaccinations), and whether logarithmic transformation of data is required. Taking Canada as an example, we can see that the number of confirmed cases, deaths and vaccinations all accumulate gradually. The number of deaths (per million) increased rapidly from the end of 2020 to the beginning of 2021, while the rate of increase slowed down after mid-March 2021. According to the vaccination chart, Canada's per hundred increased rapidly after mid-March, which to some extent shows that vaccination helped reduce the number of deaths. Second, users can also view daily histogram additions of data. Similarly, on the left side of the screen, users can select the country they want to look at, the type (cases, deaths) they want to look at and adjust the width of the histogram. Similarly, taking Canada as an example, we can observe that the number of confirmed cases in Canada is high in early January, may and September of 2021, and the number of new cases is low in March and July of 2021. The daily number of new deaths is higher from late 2020 to early 2021 and lower after March 2021.

* Tab 3 shows information on the epidemic in multiple countries. First, the user can view the cumulative distribution of the data line plot. In the left screen, users can select many countries to be observed, types of observations (cases, Deaths, vaccinations), and whether logarithmic transformation of data is required. Second, users can also view daily histogram additions of data in multiple countries. Similarly, on the left side of the screen, users can select the country they want to look at, the type (cases, deaths) they want to look at and adjust the width of the histogram. 


## 5. Statistical Analysis Inputs, Controls, and Outputs

After viewing and comparing the number of COVID-19 deaths, confirmed cases, and vaccinations in each country, we conducted an analysis in Tab4 to explore whether Healthcare and Headcount would affect vaccination in each country. By selecting the country users care about in the left box, they can view the line plot of the variation of health expenditure(% of GDP), health expenditure in public, and health expenditure per Capita in these countries from 2004 to 2014. And the line plot of how HeadCount has changed from 2004 to 2019. In addition, users can also enter the year of interest to see the country's rank table in these aspects. We found that the countries that ranked high in healthcare were United States, Marshall Islands, Tuvalu, Cuba, Brunei, Monaco, Luxembourg. As we can see from the previous chart, these countries also have high vaccination rates. A headcount table showed that a high percentage of families are thought to have incomes below the poverty line in South Sudan, Madagascar and Congo. As we can see from the previous chart, these countries also have low vaccination rates. Therefore, we think that a country's healthcare level and headcount index have an impact on vaccination rates.

## 6. References

* Lindstrom, M. (2020). A commentary on “The trouble with trust: Time-series analysis of social capital, income inequality, and COVID-19 deaths in 84 countries.” *Social Science & Medicine (1982), 263*, 113386–113386. https://doi.org/10.1016/j.socscimed.2020.113386

* Hussain, W. (2021). COVID-19 Vaccination Challenges in Developing Countries.*The International Journal of Frontier Sciences, 5*(1). https://doi.org/10.37978/tijfs.v5i1.356

* Alhinai, Z. & Elsidig, N. (2021). Countries with similar COVID-19 vaccination rates yet divergent outcomes: are all vaccines created equal? *International Journal of Infectious Diseases, 110*, 258–260. https://doi.org/10.1016/j.ijid.2021.06.040

* Wang, W., Wu, Q., Yang, J., Dong, K., Chen, X., Bai, X., Chen, X., Chen, Z., Viboud, C., Ajelli, M., & Yu, H. (2020). Global, regional, and national estimates of target population sizes for covid-19 vaccination: descriptive study. *BMJ, 371*, m4704–m4704. https://doi.org/10.1136/bmj.m4704























